spring.application.name=ai-operations
server.servlet.context-path=/ai-operations
spring.profiles.active=@spring.profiles.active@
spring.config.import=optional:nacos:ai-operations.properties

spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.import-check.enabled=false
spring.cloud.nacos.config.group=${spring.application.name}
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.discovery.service=${spring.application.name}
spring.cloud.nacos.discovery.group=${spring.application.name}

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

dubbo.application.name=${spring.application.name}
dubbo.protocol.name=tri
dubbo.protocol.port=20860
dubbo.registry.address=nacos://${spring.cloud.nacos.discovery.server-addr}
dubbo.config-center.address=nacos://${spring.cloud.nacos.config.server-addr}
dubbo.scan.base-packages=com.ai.operations

